- name: Setup Redis and Frontend Servers
  hosts:
    - server_role_redis_server
    - server_role_frontend_server
  become: true
  gather_facts: yes # Collect facts only once for the entire play
  vars:
    # Set remote_user conditionally for each server role
    ansible_user: "{{ 'rocky' if 'server_role_redis_server' in group_names else 'ubuntu' }}"
  tasks:
    - name: Use frontend role
      include_role: 
        name: frontend
      when: "'server_role_frontend_server' in group_names and ansible_facts['distribution'] == 'Ubuntu'"
    # Tasks for Redis Servers
    - name: Use backend role
      include_role: 
        name: backend
      when: "'server_role_redis_server' in group_names and ansible_facts['distribution'] == 'Rocky'"
